import {
  BadRequestException,
  ConflictException,
  HttpException,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import {
  InterviewStatus,
  InterviewType,
  MessageRole,
  Prisma,
} from '@prisma/client';
import type {
  CodingSubmission,
  InterviewMessage,
  InterviewReport,
  User,
} from '@prisma/client';
import type { Response } from 'express';
import { AiService } from '../ai/ai.service';
import type { ChatMessage } from '../ai/chat-provider';
import { TOPIC_DRIVEN_TYPES } from '../ai/interview.constants';
import { CodingService, redactHiddenResults } from '../coding/coding.service';
import { getProblemById } from '../coding/coding.problems';
import { SseWriter } from '../common/sse';
import { PrismaService } from '../prisma/prisma.service';
import { computeStreak } from './streak';
import {
  CreateInterviewDto,
  RecordEventDto,
  SendMessageDto,
  SubmitCodingDto,
} from './dto/interview.dto';
import {
  MAX_CANDIDATE_TURNS,
  allowedActions,
  buildInterviewPlan,
  deriveTurnState,
  groupTranscript,
  interviewerMetaFor,
  progressFor,
  readInterviewerMeta,
  resolveAction,
  resolvePlan,
  transitionFor,
  type CandidateMeta,
  type InterviewConfig,
  type InterviewerMeta,
  type TurnAction,
} from './interview-plan';
import {
  assembleReport,
  computeCodingScore,
  evaluatorDimensions,
  weakAreaDeltas,
} from './evaluation';
import { TurnStreamParser, sanitizeReply, tagFor } from './turn-protocol';

/** Older turns beyond this are dropped from the model context. */
const HISTORY_MESSAGES = 30;
/** Completed interviews considered when recomputing the daily streak. */
const STREAK_LOOKBACK = 400;

const TRANSCRIPT_INCLUDE = {
  messages: { orderBy: [{ createdAt: 'asc' }, { id: 'asc' }] },
  report: true,
  codingSubs: { orderBy: { createdAt: 'asc' } },
  events: { orderBy: { createdAt: 'asc' } },
} satisfies Prisma.InterviewInclude;

type InterviewWithTranscript = Prisma.InterviewGetPayload<{
  include: typeof TRANSCRIPT_INCLUDE;
}>;

export interface CompletionResult {
  status: InterviewStatus;
  report: InterviewReport | null;
}

const KIND_TO_ACTION: Record<InterviewerMeta['kind'], TurnAction> = {
  question: 'NEXT',
  follow_up: 'FOLLOW_UP',
  closing: 'END',
};

@Injectable()
export class InterviewsService {
  private readonly logger = new Logger('InterviewsService');
  /** Interviews with a reply currently being generated by this process. */
  private readonly turnsInFlight = new Set<string>();
  /** Concurrent completion requests share one evaluation per process. */
  private readonly completionsInFlight = new Map<
    string,
    Promise<CompletionResult>
  >();

  constructor(
    private prisma: PrismaService,
    private ai: AiService,
    private codingService: CodingService,
  ) {}

  // -------------------------------------------------------------------------
  // Create / read
  // -------------------------------------------------------------------------

  async create(user: User, dto: CreateInterviewDto) {
    const topicDriven = TOPIC_DRIVEN_TYPES.includes(dto.type);
    const topics = topicDriven ? [...new Set(dto.topics)] : [];
    if (topicDriven && topics.length === 0) {
      throw new BadRequestException(
        'Select at least one topic for a technical or mixed interview.',
      );
    }

    const resume =
      dto.includeResume === false
        ? null
        : await this.resolveResume(user, dto.resumeId);

    const weakAreas = await this.prisma.userWeakArea.findMany({
      where: { userId: user.id, struggleCount: { gt: 0 } },
      orderBy: [{ struggleCount: 'desc' }, { lastSeenAt: 'desc' }],
      take: 5,
      select: { topic: true },
    });

    const plan = buildInterviewPlan({
      type: dto.type,
      experience: dto.experience,
      difficulty: dto.difficulty,
      personality: dto.personality,
      topics,
      weakAreas: weakAreas.map((w) => w.topic),
      hasResume: resume !== null,
    });

    const config: InterviewConfig = {
      role: dto.role,
      experience: dto.experience,
      type: dto.type,
      difficulty: dto.difficulty,
      personality: dto.personality,
      topics,
      includeCoding: topicDriven && (dto.includeCoding ?? true),
      includeResume: resume !== null,
      examMode: dto.examMode ?? false,
      plan,
    };

    // The opening falls back to a deterministic question if the model is
    // down, so starting an interview never depends on the AI being up.
    const opening = await this.ai.generateOpening(
      config,
      plan,
      resume?.content,
    );
    const openingMeta: InterviewerMeta = { kind: 'question', planIndex: 0 };

    const interview = await this.prisma.interview.create({
      data: {
        userId: user.id,
        role: dto.role,
        experience: dto.experience,
        type: dto.type as InterviewType,
        difficulty: dto.difficulty,
        personality: dto.personality,
        topics,
        resumeId: resume?.id ?? null,
        config: config as unknown as Prisma.InputJsonValue,
        status: InterviewStatus.IN_PROGRESS,
        startedAt: new Date(),
        messages: {
          create: {
            role: MessageRole.INTERVIEWER,
            content: opening,
            metadata: openingMeta as unknown as Prisma.InputJsonValue,
          },
        },
      },
    });

    return { interview, openingMessage: opening };
  }

  findAll(user: User) {
    return this.prisma.interview.findMany({
      where: { userId: user.id },
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        role: true,
        type: true,
        difficulty: true,
        personality: true,
        status: true,
        createdAt: true,
        completedAt: true,
        report: { select: { overallScore: true, readinessPercent: true } },
      },
    });
  }

  async findOne(user: User, id: string) {
    return this.present(await this.loadTranscript(user, id));
  }

  // -------------------------------------------------------------------------
  // Turns
  // -------------------------------------------------------------------------

  /**
   * Streams the interviewer's reply to one candidate answer over SSE.
   *
   * Reliability guarantees:
   * - Nothing is persisted unless the reply is complete; on failure the client
   *   receives an `error` frame and can retry the same answer.
   * - The turn (answer + reply) is saved atomically *before* the final `turn`
   *   frame, so a reload right after the stream always shows it.
   * - Retrying with the same `clientMessageId` replays the saved reply rather
   *   than creating a duplicate turn (e.g. after a dropped connection).
   * - Writes are guarded by optimistic concurrency on the interview row, so a
   *   second tab or a concurrent completion cannot interleave turns.
   */
  async sendMessage(
    user: User,
    id: string,
    dto: SendMessageDto,
    res: Response,
  ): Promise<void> {
    const interview = await this.loadTranscript(user, id);
    this.assertInProgress(interview.status);

    const config = interview.config as unknown as InterviewConfig;
    const plan = resolvePlan(config);
    const state = deriveTurnState(interview.messages);

    if (dto.clientMessageId) {
      const replay = findSavedTurn(interview.messages, dto.clientMessageId);
      if (replay) {
        const sse = new SseWriter(res);
        sse.send({ content: replay.interviewer.content });
        sse.send({
          turn: {
            candidate: replay.candidate,
            interviewer: replay.interviewer,
            progress: progressFor(plan, state),
          },
        });
        sse.done();
        return;
      }
    }

    if (state.concluded) {
      throw new ConflictException(
        'The interview is over. End the session to see your report.',
      );
    }
    if (state.candidateTurns >= MAX_CANDIDATE_TURNS) {
      throw new ConflictException(
        'This interview has reached its maximum length. End the session to see your report.',
      );
    }
    if (this.turnsInFlight.has(id)) {
      throw new ConflictException(
        'Your previous answer is still being processed. Please wait a moment.',
      );
    }

    this.turnsInFlight.add(id);
    try {
      await this.runTurn(user, interview, dto, res);
    } finally {
      this.turnsInFlight.delete(id);
    }
  }

  private async runTurn(
    user: User,
    interview: InterviewWithTranscript,
    dto: SendMessageDto,
    res: Response,
  ): Promise<void> {
    const receivedAt = new Date();
    const config = interview.config as unknown as InterviewConfig;
    const plan = resolvePlan(config);
    const state = deriveTurnState(interview.messages);
    const allowed = allowedActions(plan, state);
    const resumeContent = await this.resumeContent(user, interview.resumeId);

    const sse = new SseWriter(res);
    sse.open();

    const parser = new TurnStreamParser();
    let shown = '';
    try {
      const stream = this.ai.streamTurn({
        config,
        plan,
        state,
        allowed,
        history: toModelHistory(interview.messages, dto.content),
        resumeContent,
      });
      for await (const chunk of stream) {
        const text = parser.push(chunk);
        if (text) {
          shown += text;
          sse.send({ content: text });
        }
      }
      const tail = parser.flush();
      if (tail) {
        shown += tail;
        sse.send({ content: tail });
      }
    } catch (error) {
      sse.fail(
        error instanceof HttpException
          ? error.message
          : 'The interviewer is temporarily unavailable. Please try again.',
        'AI_UNAVAILABLE',
      );
      return;
    }

    let reply = sanitizeReply(shown);
    if (!reply) {
      // Typical of reasoning models that spend the output budget on hidden
      // thinking; worth surfacing to whoever operates the deployment.
      this.logger.warn(
        `Interview ${interview.id}: model returned no visible reply text`,
      );
      sse.fail(
        'The interviewer did not respond. Please try again.',
        'EMPTY_REPLY',
      );
      return;
    }

    const action = resolveAction(parser.action, allowed);
    if (parser.action !== action) {
      this.logger.warn(
        `Interview ${interview.id}: model chose ${parser.action ?? 'no tag'}, applied ${action}`,
      );
    }
    const transition = transitionFor(action, parser.action, plan, state);
    if (transition) {
      sse.send({ content: `\n\n${transition}` });
      reply = `${reply}\n\n${transition}`;
    }

    const candidateMeta: CandidateMeta = {
      planIndex: state.planIndex,
      ...(dto.clientMessageId ? { clientMessageId: dto.clientMessageId } : {}),
    };

    let saved: {
      candidate: InterviewMessage;
      interviewer: InterviewMessage;
    } | null;
    try {
      saved = await this.persistTurn(interview, {
        receivedAt,
        answer: dto.content,
        candidateMeta,
        reply,
        interviewerMeta: interviewerMetaFor(action, state),
      });
    } catch (error) {
      this.logger.error(
        `Failed to persist turn for interview ${interview.id}`,
        error instanceof Error ? error.stack : String(error),
      );
      sse.fail(
        'Your answer could not be saved. Please try again.',
        'SAVE_FAILED',
      );
      return;
    }

    if (!saved) {
      sse.fail(
        'This interview was updated elsewhere (another tab?). Reload the page to continue.',
        'CONFLICT',
      );
      return;
    }

    const next = deriveTurnState([
      ...interview.messages,
      saved.candidate,
      saved.interviewer,
    ]);
    sse.send({
      turn: {
        candidate: saved.candidate,
        interviewer: saved.interviewer,
        progress: progressFor(plan, next),
      },
    });
    sse.done();
  }

  private persistTurn(
    interview: InterviewWithTranscript,
    turn: {
      receivedAt: Date;
      answer: string;
      candidateMeta: CandidateMeta;
      reply: string;
      interviewerMeta: InterviewerMeta;
    },
  ) {
    return this.prisma.$transaction(async (tx) => {
      // Claim the interview: succeeds only if it is still in progress and
      // nobody else wrote a turn or completed it since we read it.
      const claimed = await tx.interview.updateMany({
        where: {
          id: interview.id,
          status: InterviewStatus.IN_PROGRESS,
          updatedAt: interview.updatedAt,
        },
        data: { updatedAt: new Date() },
      });
      if (claimed.count === 0) return null;

      const candidate = await tx.interviewMessage.create({
        data: {
          interviewId: interview.id,
          role: MessageRole.CANDIDATE,
          content: turn.answer,
          metadata: turn.candidateMeta as unknown as Prisma.InputJsonValue,
          createdAt: turn.receivedAt,
        },
      });
      // Explicit, strictly increasing timestamps keep transcript order stable.
      const interviewer = await tx.interviewMessage.create({
        data: {
          interviewId: interview.id,
          role: MessageRole.INTERVIEWER,
          content: turn.reply,
          metadata: turn.interviewerMeta as unknown as Prisma.InputJsonValue,
          createdAt: new Date(
            Math.max(Date.now(), turn.receivedAt.getTime() + 1),
          ),
        },
      });
      return { candidate, interviewer };
    });
  }

  // -------------------------------------------------------------------------
  // Completion
  // -------------------------------------------------------------------------

  complete(user: User, id: string): Promise<CompletionResult> {
    const key = `${user.id}:${id}`;
    const pending = this.completionsInFlight.get(key);
    if (pending) return pending;

    const promise = this.completeOnce(user, id).finally(() =>
      this.completionsInFlight.delete(key),
    );
    this.completionsInFlight.set(key, promise);
    return promise;
  }

  private async completeOnce(
    user: User,
    id: string,
  ): Promise<CompletionResult> {
    const interview = await this.loadTranscript(user, id);

    // Idempotent: a finished interview returns its existing outcome.
    if (interview.status === InterviewStatus.COMPLETED) {
      return { status: interview.status, report: interview.report };
    }
    if (interview.status === InterviewStatus.ABANDONED) {
      return { status: interview.status, report: null };
    }
    if (this.turnsInFlight.has(id)) {
      throw new ConflictException(
        'Please wait for the interviewer to finish replying before ending the interview.',
      );
    }

    const completedAt = new Date();
    const durationSecs = activeDurationSecs(interview);
    const answered = interview.messages.some(
      (m) => m.role === MessageRole.CANDIDATE,
    );

    // Nothing to evaluate: close it without inventing a report.
    if (!answered) {
      await this.prisma.interview.updateMany({
        where: { id, userId: user.id, status: InterviewStatus.IN_PROGRESS },
        data: { status: InterviewStatus.ABANDONED, completedAt, durationSecs },
      });
      return { status: InterviewStatus.ABANDONED, report: null };
    }

    const config = interview.config as unknown as InterviewConfig;
    const plan = resolvePlan(config);
    const groups = groupTranscript(plan, interview.messages);
    const dimensions = evaluatorDimensions(config.type, groups);

    // Throws (503) if the evaluator is unavailable or returns unusable output;
    // the interview stays IN_PROGRESS so the candidate can simply retry.
    const evaluation = await this.ai.evaluateInterview(
      {
        config,
        groups,
        dimensions,
        codingSummary: describeCoding(interview.codingSubs),
      },
      {
        dimensions,
        answeredPlanIndices: groups
          .filter((g) => g.answered)
          .map((g) => g.item.index),
      },
    );

    const report = assembleReport({
      type: config.type,
      plan,
      groups,
      evaluation,
      codingScore: computeCodingScore(interview.codingSubs),
    });

    const saved = await this.prisma.$transaction(async (tx) => {
      // State transition guard: only one completion can ever apply.
      const transitioned = await tx.interview.updateMany({
        where: { id, userId: user.id, status: InterviewStatus.IN_PROGRESS },
        data: { status: InterviewStatus.COMPLETED, completedAt, durationSecs },
      });
      if (transitioned.count === 0) return null;

      const created = await tx.interviewReport.create({
        data: {
          interviewId: id,
          overallScore: report.overallScore,
          readinessPercent: report.readinessPercent,
          communicationScore: report.communicationScore,
          technicalScore: report.technicalScore,
          confidenceScore: report.confidenceScore,
          problemSolvingScore: report.problemSolvingScore,
          behavioralScore: report.behavioralScore,
          systemDesignScore: report.systemDesignScore,
          codingScore: report.codingScore,
          strengths: report.strengths,
          weaknesses: report.weaknesses,
          knowledgeGaps: report.knowledgeGaps,
          topicsToRevise: report.topicsToRevise,
          mistakes: report.mistakes,
          learningRoadmap:
            report.learningRoadmap as unknown as Prisma.InputJsonValue,
          dimensions: report.dimensions as unknown as Prisma.InputJsonValue,
          questionFeedback:
            report.questionFeedback as unknown as Prisma.InputJsonValue,
          summary: report.summary,
        },
      });

      const deltas = weakAreaDeltas(
        report.questionFeedback,
        report.topicsToRevise,
      );
      for (const [topic, delta] of deltas) {
        if (delta > 0) {
          await tx.userWeakArea.upsert({
            where: { userId_topic: { userId: user.id, topic } },
            update: {
              struggleCount: { increment: delta },
              lastSeenAt: completedAt,
            },
            create: { userId: user.id, topic, struggleCount: delta },
          });
        } else if (delta < 0) {
          await tx.userWeakArea.updateMany({
            where: { userId: user.id, topic },
            data: { struggleCount: { decrement: -delta } },
          });
        }
      }
      await tx.userWeakArea.deleteMany({
        where: { userId: user.id, struggleCount: { lte: 0 } },
      });

      const completions = await tx.interview.findMany({
        where: {
          userId: user.id,
          status: InterviewStatus.COMPLETED,
          completedAt: { not: null },
        },
        orderBy: { completedAt: 'desc' },
        take: STREAK_LOOKBACK,
        select: { completedAt: true },
      });

      await tx.user.update({
        where: { id: user.id },
        data: {
          hoursPracticed: { increment: durationSecs / 3600 },
          streak: computeStreak(
            completions.map((c) => c.completedAt as Date),
            completedAt,
          ),
          lastActiveAt: completedAt,
        },
      });

      return created;
    });

    if (saved) return { status: InterviewStatus.COMPLETED, report: saved };

    // Another instance completed it first; return what it stored.
    const current = await this.prisma.interview.findFirst({
      where: { id, userId: user.id },
      include: { report: true },
    });
    return {
      status: current?.status ?? InterviewStatus.COMPLETED,
      report: current?.report ?? null,
    };
  }

  // -------------------------------------------------------------------------
  // Events & coding
  // -------------------------------------------------------------------------

  async recordEvent(user: User, id: string, dto: RecordEventDto) {
    const interview = await this.loadOwned(user, id);
    this.assertInProgress(interview.status);
    return this.prisma.interviewEvent.create({
      data: {
        interviewId: id,
        type: dto.type as Prisma.InterviewEventCreateInput['type'],
        metadata: dto.metadata as Prisma.InputJsonValue | undefined,
      },
    });
  }

  async submitCoding(user: User, id: string, dto: SubmitCodingDto) {
    const interview = await this.loadOwned(user, id);
    this.assertInProgress(interview.status);
    const problem = getProblemById(dto.problemId);
    if (!problem) throw new BadRequestException('Problem not found');

    const result = await this.codingService.runTests(
      dto.problemId,
      dto.code,
      dto.language,
    );

    return this.prisma.codingSubmission.create({
      data: {
        interviewId: id,
        problemId: problem.id,
        problemTitle: problem.title,
        language: dto.language,
        code: dto.code,
        difficulty: problem.difficulty,
        timeSpentSecs: dto.timeSpentSecs ?? 0,
        hintsUsed: dto.hintsUsed ?? 0,
        compileErrors: result.compileErrors,
        testsPassed: result.passed,
        testsTotal: result.total,
        testResults: result.results as unknown as Prisma.InputJsonValue,
      },
    });
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  /** Every lookup is scoped to the caller; other users' ids return 404. */
  private async loadOwned(user: User, id: string) {
    const interview = await this.prisma.interview.findFirst({
      where: { id, userId: user.id },
      select: { id: true, status: true },
    });
    if (!interview) throw new NotFoundException('Interview not found');
    return interview;
  }

  private async loadTranscript(
    user: User,
    id: string,
  ): Promise<InterviewWithTranscript> {
    const interview = await this.prisma.interview.findFirst({
      where: { id, userId: user.id },
      include: TRANSCRIPT_INCLUDE,
    });
    if (!interview) throw new NotFoundException('Interview not found');
    return interview;
  }

  private assertInProgress(status: InterviewStatus) {
    if (status !== InterviewStatus.IN_PROGRESS) {
      throw new ConflictException(
        status === InterviewStatus.COMPLETED
          ? 'This interview is already completed.'
          : 'This interview has ended.',
      );
    }
  }

  private present(interview: InterviewWithTranscript) {
    const config = interview.config as unknown as InterviewConfig | null;
    const plan = config ? resolvePlan(config) : null;
    return {
      ...interview,
      // The plan's guidance is interviewer-only; expose just the agenda.
      config: config ? { ...config, plan: undefined } : null,
      plan: plan
        ? plan.items.map(({ index, kind, focus }) => ({ index, kind, focus }))
        : [],
      progress: plan
        ? progressFor(plan, deriveTurnState(interview.messages))
        : null,
      codingSubs: interview.codingSubs.map((s) => ({
        ...s,
        testResults: redactHiddenResults(s.testResults),
      })),
    };
  }

  private async resolveResume(user: User, resumeId?: string) {
    const select = { id: true, content: true };
    if (resumeId) {
      const resume = await this.prisma.resume.findFirst({
        where: { id: resumeId, userId: user.id },
        select,
      });
      if (!resume) throw new BadRequestException('Resume not found');
      return resume;
    }
    return this.prisma.resume.findFirst({
      where: { userId: user.id, isActive: true },
      orderBy: { createdAt: 'desc' },
      select,
    });
  }

  private async resumeContent(
    user: User,
    resumeId: string | null,
  ): Promise<string | undefined> {
    if (!resumeId) return undefined;
    const resume = await this.prisma.resume.findFirst({
      where: { id: resumeId, userId: user.id },
      select: { content: true },
    });
    return resume?.content;
  }
}

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/** Replays prior turns to the model, re-attaching the control tags it used. */
function toModelHistory(
  messages: InterviewMessage[],
  answer: string,
): ChatMessage[] {
  const history: ChatMessage[] = [];
  for (const m of messages) {
    if (m.role === MessageRole.CANDIDATE) {
      history.push({ role: 'user', content: m.content });
    } else if (m.role === MessageRole.INTERVIEWER) {
      const meta = readInterviewerMeta(m.metadata);
      const tag = meta ? `${tagFor(KIND_TO_ACTION[meta.kind])} ` : '';
      history.push({ role: 'assistant', content: `${tag}${m.content}` });
    }
  }
  history.push({ role: 'user', content: answer });
  return history.slice(-HISTORY_MESSAGES);
}

function findSavedTurn(messages: InterviewMessage[], clientMessageId: string) {
  const index = messages.findIndex(
    (m) =>
      m.role === MessageRole.CANDIDATE &&
      (m.metadata as CandidateMeta | null)?.clientMessageId === clientMessageId,
  );
  if (index === -1) return null;
  const interviewer = messages
    .slice(index + 1)
    .find((m) => m.role === MessageRole.INTERVIEWER);
  return interviewer ? { candidate: messages[index], interviewer } : null;
}

/**
 * Time actually spent: from start to the last recorded activity, so leaving
 * a tab open for a day does not count as a day of practice.
 */
function activeDurationSecs(interview: InterviewWithTranscript): number {
  if (!interview.startedAt) return 0;
  const activity = [
    ...interview.messages.map((m) => m.createdAt.getTime()),
    ...interview.codingSubs.map((s) => s.createdAt.getTime()),
  ];
  const last = activity.length > 0 ? Math.max(...activity) : 0;
  return Math.max(0, Math.floor((last - interview.startedAt.getTime()) / 1000));
}

function describeCoding(submissions: CodingSubmission[]): string | null {
  if (submissions.length === 0) return null;
  const byProblem = new Map<string, CodingSubmission[]>();
  for (const s of submissions) {
    byProblem.set(s.problemId, [...(byProblem.get(s.problemId) ?? []), s]);
  }
  return [...byProblem.values()]
    .map((attempts) => {
      const best = attempts.reduce((a, b) =>
        b.testsTotal > 0 &&
        b.testsPassed / b.testsTotal >=
          a.testsPassed / Math.max(a.testsTotal, 1)
          ? b
          : a,
      );
      const hints = Math.max(...attempts.map((a) => a.hintsUsed));
      return `- ${best.problemTitle} (${best.difficulty}, ${best.language}): best run passed ${best.testsPassed}/${best.testsTotal} tests over ${attempts.length} attempt(s), ${hints} hint(s) used`;
    })
    .join('\n');
}
